#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# default cursor
xsetroot -cursor_name left_ptr &

# restart picom
picom -f &

#launch toolbar
eww open bar &

# set background
feh --bg-fill $HOME/Downloads/Wallpapers/wallhaven-odmmyl.jpg &

# clear rules
bspc rule -r '*' &

# add monitors
bspc monitor -d I II III IV VPN 

bspc config border_width           2
bspc config window_gap             12

bspc config split_ratio            0.5
bspc config borderless_monocle     true
bspc config gapless_monocle        true
bspc config focus_follows_pointer  true

bspc rule -a AmneziaVPN desktop='VPN'
bspc rule -a '*:*:Picture-in-Picture' state=floating sticky=on
